package io.jirrafe.core.knowledge

import io.jirrafe.core.model.EdgeKind
import io.jirrafe.core.model.Node
import io.jirrafe.core.model.NodeKind
import io.jirrafe.core.model.Origin
import io.jirrafe.core.store.GraphStore

/** `GRAPH_REPORT.md`: the map an agent reads first. Deterministic, sized for a token budget. */
object Report {
    private const val MAX_PER_KIND = 25

    fun markdown(store: GraphStore, r: Knowledge.Result): String = buildString {
        val g = r.g
        val modules = store.nodes(NodeKind.MODULE)
        val artifacts = store.nodes(NodeKind.ARTIFACT).filter { it.origin != Origin.EXTERNAL }
        val classesByUnit = g.classes.groupingBy { it.module?.let { m -> "module:$m" } ?: it.artifact?.let { a -> "artifact:$a" } ?: "" }.eachCount()
        val root = store.meta("root").orEmpty()

        appendLine("# Graph report")
        appendLine()
        appendLine("Generated by jirrafe from ${store.count("nodes")} nodes and ${store.count("edges")} edges (${store.meta("buildTool") ?: "?"} build at `${store.meta("root")}`).")
        appendLine()
        appendLine("## Overview")
        appendLine()
        appendLine("- Modules: ${modules.size} (${modules.joinToString { it.fqn }})")
        appendLine("- Internal jars: ${artifacts.size}")
        appendLine("- Classes analysed: ${r.classCount} (repo ${g.classes.count { it.origin == Origin.REPO }}, sources jar ${g.classes.count { it.origin == Origin.SOURCES_JAR }}, bytecode only ${g.classes.count { it.origin == Origin.BYTECODE }})")
        appendLine("- Communities: ${r.leafCommunities().size} at the finest level (hierarchy depth ${r.levels})")
        appendLine("- Layers: ${Layers.ORDER.filter { it in r.layerCounts() }.joinToString { "$it ${r.layerCounts()[it]}" }}")
        appendLine("- Flows: ${r.flowCount}; findings: ${r.findingCount} (${r.findings.groupingBy { it.severity }.eachCount().entries.sortedBy { it.key }.joinToString { "${it.value} ${it.key}" }})")
        appendLine("- Test links: ${r.tests.size}")
        appendLine()

        appendLine("## Modules")
        appendLine()
        appendLine("| module | coordinates | classes | internal dependencies |")
        appendLine("|---|---|---|---|")
        for (m in modules) {
            val deps = store.edgesFrom(m.id, EdgeKind.DEPENDS_ON_ARTIFACT).map { it.to }
                .filter { d -> d.startsWith("module:") || artifacts.any { it.id == d } }
            appendLine("| ${m.fqn} | ${m.attrs["group"]}:${m.attrs["version"]} | ${classesByUnit[m.id] ?: 0} | ${deps.joinToString { it.removePrefix("artifact:").removePrefix("module:") }} |")
        }
        appendLine()

        appendLine("## Internal jars")
        appendLine()
        if (artifacts.isEmpty()) appendLine("None.") else {
            appendLine("| artifact | source | classes | used by |")
            appendLine("|---|---|---|---|")
            for (a in artifacts) {
                val users = store.edgesTo(a.id, EdgeKind.DEPENDS_ON_ARTIFACT).map { it.from.removePrefix("module:") }
                appendLine("| ${a.fqn} | ${a.origin.name.lowercase().replace('_', ' ')} | ${classesByUnit[a.id] ?: 0} | ${users.joinToString()} |")
            }
        }
        appendLine()

        appendLine("## Communities")
        appendLine()
        val roots = r.communities.filter { it.parent == null }.sortedByDescending { it.members.size }
        fun tree(c: Knowledge.Community, indent: String) {
            val gods = c.gods.joinToString { g.shortName(g.classes[it].id) }
            val node = store.node(c.id)
            val label = node?.attrs?.get("llmLabel") ?: c.label
            appendLine("$indent- `${c.id}` **$label**: ${c.members.size} classes" + (if (gods.isNotEmpty()) "; central: $gods" else ""))
            node?.attrs?.get("llmSummary")?.let { appendLine("$indent  $it") }
            for (child in c.children.sortedByDescending { it.members.size }.take(30)) tree(child, "$indent  ")
        }
        for (c in roots.take(30)) tree(c, "")
        if (roots.size > 30) appendLine("- ... and ${roots.size - 30} more")
        appendLine()

        appendLine("## God nodes")
        appendLine()
        appendLine("| class | layer | in-degree | betweenness | community | tested |")
        appendLine("|---|---|---|---|---|---|")
        val tested = r.tests.map { it.to }.toSet()
        for (i in r.gods) {
            val c = g.classes[i]
            val community = r.leafCommunities().firstOrNull { i in it.members }?.id ?: ""
            appendLine("| `${c.id}` | ${r.layers[i] ?: ""} | ${r.scores.inDegree[i]} | ${"%.1f".format(r.scores.betweenness[i])} | $community | ${if (c.id in tested) "yes" else "no"} |")
        }
        appendLine()

        appendLine("## Layers")
        appendLine()
        appendLine("| layer | classes | examples |")
        appendLine("|---|---|---|")
        for (layer in Layers.ORDER) {
            val members = g.classes.indices.filter { r.layers[it] == layer }
            if (members.isEmpty()) continue
            appendLine("| $layer | ${members.size} | ${members.take(5).joinToString { g.shortName(g.classes[it].id) }} |")
        }
        appendLine()

        appendLine("## Flows")
        appendLine()
        if (r.flows.isEmpty()) appendLine("No entry points found.") else {
            appendLine("| entry | steps | path |")
            appendLine("|---|---|---|")
            for (f in r.flows.take(200)) {
                val llm = store.node("flow:${f.entry.id}")?.attrs?.get("llmSummary")
                appendLine("| ${f.label} (`flow:${f.entry.id}`) | ${f.steps.size} | ${llm ?: Flows.summary(g, f).substringAfter(": ")} |")
            }
            if (r.flows.size > 200) appendLine("| ... and ${r.flows.size - 200} more | | |")
        }
        appendLine()

        appendLine("## Findings")
        appendLine()
        val all = store.nodes(NodeKind.FINDING)
        if (all.isEmpty()) appendLine("None.")
        for ((kind, list) in all.groupBy { it.attrs["kind"] ?: "other" }.entries.sortedBy { it.key }) {
            appendLine("### $kind (${list.size})")
            appendLine()
            val sorted = list.sortedWith(compareBy({ SEVERITY.indexOf(it.attrs["severity"]) }, { it.id }))
            for (f in sorted.take(MAX_PER_KIND)) appendLine("- ${f.attrs["severity"]}: ${f.fqn}${location(f, root)}")
            if (sorted.size > MAX_PER_KIND) appendLine("- ... and ${sorted.size - MAX_PER_KIND} more")
            appendLine()
        }
    }

    private val SEVERITY = listOf("error", "warning", "info")

    private fun location(n: Node, root: String): String = n.file?.let { f ->
        val rel = f.removePrefix(root).trimStart('/', '\\').replace('\\', '/')
        " (`$rel${n.startLine?.let { l -> ":$l" } ?: ""}`)"
    } ?: ""
}
